name = "QuantumEspressoAnalysis"
uuid = "cb7bdcfd-802d-475c-b8aa-bf547d429cd7"
authors = ["Rashid Rafeek <rashidrafeek@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
